# -*- coding: utf-8 -*-
"""No.  1b

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cLeWcHtsbn0XNqMwK_aQnQDXMtMD6BAa
"""

#Azkia Kamila ; 21091397027 ; 2021A
#No. 1b

#multiple perceptron/neuron

#inisialisasi numpy
import numpy as np

#inisialisasi variabel
inputs = [2.0, 3.0, 2.5, 1.2, 9.5, 5.0, 6.1, 7.3, 4.1, 8.7]

weights = [[-0.25, 2.5, 5.3, 9.2, -6.1, 8.0, 1.5, 7.3, 9.9, 5.1],
           [-0.5, 5.6, 7.8, 3.2, 9.1, 6.4, -7.3, 0.5, 1.9, 2.7],
           [9.5, -0.3, 0.65, -7.3, 5.1, 2.0, 7.0, -6.0, 5.0, 4.0],
           [-0.2, 4.1, 5.0, 3.0, 1.0, -8.6, 2.8, -9.0, 4.1, 0.35],
           [-0.05, 1.0, 3.0, -8.1, 6.4, 9.0, 7.3, 4.5, 6.2, -0.32]]

biases = [9.0, 0.3, 0.2, 1.5, 8.4]

#output
output = np.dot(weights, inputs) + biases

#print output
print(output)