# -*- coding: utf-8 -*-
"""No. 1a

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yYWCC9FTUa_uiJ-KQPVWRxLqy8ZPWuPb
"""

#Azkia Kamila ; 21091397027 ; 2021A
#No. 1a

#single perceptron/neuron

#inisialisasi numpy
import numpy as np

#inisialisasi variabel
inputs = [2.0, 3.0, 2.5, 1.2, 9.5, 5.0, 6.1, 7.3, 4.1, 8.7]
weights = [-0.25, 2.5, 5.3, 9.2, -6.1, 8.0, 1.5, 7.3, 9.9, 5.1]
bias = 9.0

#output
output = np.dot(weights, inputs) + bias

#print output
print(output)