# -*- coding: utf-8 -*-
"""No. 1c

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NKxYk6sLenbnrNdngkkEP0XuCILz-VBK
"""

#Azkia Kamila ; 21091397027 ; 2021A
#No. 1c

#multiple perceptron/neuron batch

#inisialisasi numpy
import numpy as np

#inisialisasi variabel (input 10 ; batch 6 = matrix 6*10)
inputs = [[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 1.5],
          [3.0, 5.0, 5.1, 4.6, 6.5, 7.0, 9.9, 1.7, 7.9, 3.0],
          [0.1, 0.3, 5.0, 6.1, 7.8, 5.1, 9.8, 4.3, 5.0, 3.2],
          [0.3, 5.3, 9.0, 6.3, 7.8, 5.5, 6.1, 3.7, 9.2, 6.8],
          [2.0, 9.6, 4.2, 2.9, 5.3, 6.4, 5.0, 6.9, 0.7, 0.5],
          [0.2, 5.1, 4.3, 4.9, 9.6, 7.0, 6.0, 8.6, 4.3, 1.9]]

#panjang weights = panjang inputs(10) ; jumlah weights = jumlah neuron(5)
weights = [[-0.25, 2.5, 5.3, 9.2, -6.1, 8.0, 1.5, 7.3, 9.9, 5.1],
           [-0.5, 5.6, 7.8, 3.2, 9.1, 6.4, -7.3, 0.5, 1.9, 2.7],
           [9.5, -0.3, 0.65, -7.3, 5.1, 2.0, 7.0, -6.0, 5.0, 4.0],
           [-0.2, 4.1, 5.0, 3.0, 1.0, -8.6, 2.8, -9.0, 4.1, 0.35],
           [-0.05, 1.0, 3.0, -8.1, 6.4, 9.0, 7.3, 4.5, 6.2, -0.32]]

#jumlah bias = jumlah neuron(5)
biases = [9.0, 0.3, 0.2, 1.5, 8.4]

#ouputs
layer_outputs = np.dot(inputs, np.array(weights).T) + biases

#print ouputs
print(layer_outputs)